#!/bin/sh

# extra packages usually added to a new project can be added here

yarn add lodash @types/lodash moment-timezone @types/moment styled-components @types/styled-components

# yarn add @react-navigation/native
