#!/bin/sh

# extra packages usually added to a new project can be added here

# @react-navigation/native needs => react-native-screens react-native-safe-area-context
# @react-navigation/stack  needs => react-native-gesture-handler

yarn add moment-timezone styled-components react-native-svg \
  react-native-screens react-native-safe-area-context react-native-gesture-handler \
  @react-navigation/native @react-navigation/bottom-tabs @react-navigation/stack \
  @react-native-async-storage/async-storage

yarn add -D @types/moment @types/styled-components @types/styled-components-react-native \
  @svgr/cli
