#!/bin/sh

ANDROID_SECRETS_FOLDER=.secrets_android
IOS_SECRETS_FOLDER=.secrets_ios


android_key_create() {
  if [ "$ANDROID_KEY_FILE" = "" ]; then echo "ANDROID_KEY_FILE can not be blank"; exit; fi
  if [ "$ANDROID_ALIAS_NAME" = "" ]; then echo "ANDROID_ALIAS_NAME can not be blank"; exit; fi
  if [ "$ANDROID_KEY_INFO" = "" ]; then echo "ANDROID_KEY_INFO can not be blank"; exit; fi
  if [ "$ANDROID_KEYSTORE_PASSWORD" = "" ]; then echo "ANDROID_KEYSTORE_PASSWORD can not be blank"; exit; fi
  if [ "$ANDROID_ALIAS_PASSWORD" = "" ]; then echo "ANDROID_ALIAS_PASSWORD can not be blank"; exit; fi

  mkdir -p $PWD/$ANDROID_SECRETS_FOLDER

  KEY_FILE_FULLPATH="$PWD/$ANDROID_SECRETS_FOLDER/$ANDROID_KEY_FILE"

  keytool -genkey -v -keystore $KEY_FILE_FULLPATH \
    -alias $ANDROID_ALIAS_NAME \
    -keyalg RSA -keysize 2048 -validity 10000 \
    -dname "$ANDROID_KEY_INFO" \
    -storepass $ANDROID_KEYSTORE_PASSWORD -keypass $ANDROID_ALIAS_PASSWORD

  ANDROID_KEYSTORE_BASE64=$(base64 $PWD/$ANDROID_SECRETS_FOLDER/$ANDROID_KEY_FILE | tr '\n' '~')
  
  echo "# Add this to your CI/CD environment variables\nANDROID_KEYSTORE_BASE64=$ANDROID_KEYSTORE_BASE64" > ${KEY_FILE_FULLPATH}.env
}

android_key_test() {
  # read keystore file and password from environment file
  keytool -v -list -keystore $ANDROID_KEY_FILE -storepass $ANDROID_KEYSTORE_PASSWORD -alias $ANDROID_ALIAS_NAME -keypass $ANDROID_ALIAS_PASSWORD | grep 'Valid from'
  if [ $? = 0 ]; then echo "SUCCESS: Key and password match"; else echo "FAIL: Key test failed"; fi
}

# Patches the android app/build.gradle file to sign release builds with a production key and enable Hermes engine
android_patch_app_build_gradle() {
COMMENT="## Updates the android/app/build.gradle file. Replace the buildTypes block inside the android block with:
   signingConfigs {
        release {
            Properties keyProperties = new Properties()
            def keystorePropertiesFile = rootProject.file('key.properties')
            if (keystorePropertiesFile.exists()) {
                keyProperties.load(keystorePropertiesFile.newDataInputStream())
                keyAlias keyProperties.getProperty('keyAlias')
                keyPassword keyProperties.getProperty('keyPassword')
                storeFile keyProperties['storeFile'] ? file(keyProperties['storeFile']) : null
                storePassword keyProperties.getProperty('storePassword')
            }
        }
   }
   buildTypes {
       release {
           signingConfig signingConfigs.release
       }
   }
"

  APP_BUILD_FILE=./android/app/build.gradle
  echo "Updating $APP_BUILD_FILE"
  # Make backup of original file
  if [ ! -f "${APP_BUILD_FILE}_original" ]; then cp $APP_BUILD_FILE ${APP_BUILD_FILE}_original; fi

  # compile tool
  cd _tools ; javac android_multitool.java ; cd ..

  # Update signingConfigs
  export SEARCH="    signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }"
   export REPLACE="    signingConfigs {
        // ### SCRIPTED PATCH
        release {
            Properties keyProperties = new Properties()
            def keystorePropertiesFile = rootProject.file('key.properties')
            if (keystorePropertiesFile.exists()) {
                keyProperties.load(keystorePropertiesFile.newDataInputStream())
                keyAlias keyProperties.getProperty('keyAlias')
                keyPassword keyProperties.getProperty('keyPassword')
                storeFile keyProperties['storeFile'] ? file(keyProperties['storeFile']) : null
                storePassword keyProperties.getProperty('storePassword')
            }
        }
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }"
  java -cp _tools/ android_multitool replace android/app/build.gradle

  # Update buildTypes
  export SEARCH="    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            // Caution! In production, you need to generate your own keystore file.
            // see https://reactnative.dev/docs/signed-apk-android.
            signingConfig signingConfigs.debug"
  export REPLACE="    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            // ### SCRIPTED PATCH
            signingConfig signingConfigs.release"
  
  java -cp _tools/ android_multitool replace android/app/build.gradle
}

android_key_add() {
  echo "storePassword=$ANDROID_KEYSTORE_PASSWORD
keyPassword=$ANDROID_ALIAS_PASSWORD
keyAlias=$ANDROID_ALIAS_NAME
storeFile=$PWD/$ANDROID_KEY_FILE
" > $PWD/android/key.properties

  FULL_KEYFILE_PATH=$PWD/$ANDROID_KEY_FILE
  echo $FULL_KEYFILE_PATH
  echo $ANDROID_KEYSTORE_BASE64 | base64 --decode > $FULL_KEYFILE_PATH
}

android_key_remove() {
  FULL_KEYFILE_PATH=$PWD/$ANDROID_KEY_FILE
  rm -f $FULL_KEYFILE_PATH
}


ios_patch_podfile() {
  IOS_POD_FILE=./ios/Podfile
  echo "Updating $IOS_POD_FILE"
  if [ ! -f "${IOS_POD_FILE}_original" ]; then cp $IOS_POD_FILE ${IOS_POD_FILE}_original; fi

  awk '/:hermes_enabled => false/{gsub(/false/,"true")};{print}' ${IOS_POD_FILE}_original > $IOS_POD_FILE
}

ios_build_ipa() {

echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">
<plist version=\"1.0\">
<dict>
        <key>destination</key>
        <string>export</string>
        <key>method</key>
        <string>app-store</string>
        <key>provisioningProfiles</key>
        <dict>
                <key>$APP_BUNDLEID</key>
                <string>$IOS_PROV_PROFILE_NAME</string>
        </dict>
        <key>signingCertificate</key>
        <string>Apple Distribution</string>
        <key>signingStyle</key>
        <string>manual</string>
        <key>stripSwiftSymbols</key>
        <true/>
        <key>teamID</key>
        <string>$IOS_TEAM_ID</string>
        <key>uploadSymbols</key>
        <true/>
</dict>
</plist>" > $IOS_TMP_FOLDER/export_options.plist
  flutter build ipa --release --export-options-plist=$IOS_TMP_FOLDER/export_options.plist --obfuscate --split-debug-info build/app/outputs/debug-ios/
}

ios_get_secrets() {
  echo "Getting signing certificate and provisioning profile"
  echo "$IOS_KEYCHAIN_PASSWORD" | gpg --batch --yes --passphrase-fd 0 ios_secrets.tgz.gpg
  tar -zxvf ios_secrets.tgz --no-same-owner
  rm ios_secrets.tgz

  # Move provisioning profile to the right location
  mkdir -pv ~/Library/MobileDevice/Provisioning\ Profiles
  cp $IOS_TMP_FOLDER/*.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles

  # DEBUG-TMP show folder contents
  # ls -al $IOS_TMP_FOLDER
}

ios_key_add() {
  echo "Adding signing certificate and provisioning profile"

  ios_get_secrets

  # output build/ios/iphoneos/Runner.app
  # To list all identities: security find-identity -v -p codesigning
  # security list-keychains
  KEYCHAIN_FULLNAME="${IOS_KEYCHAIN_NAME}-db"

  # create and append keychain to the search list
  security create-keychain -p "$IOS_KEYCHAIN_PASSWORD" "$KEYCHAIN_FULLNAME"
  security list-keychains -d user -s "$KEYCHAIN_FULLNAME" $(security list-keychains -d user | sed s/\"//g)
  # Unlock the keychain
  security set-keychain-settings -t 3600 -l "$KEYCHAIN_FULLNAME"
  security unlock-keychain -p "$IOS_KEYCHAIN_PASSWORD" "$KEYCHAIN_FULLNAME"
  
  # Import certificate
  # echo $IOS_CERT_P12_BASE64 | base64 --decode > $IOS_TMP_FOLDER/ios_cert.p12
  security import $IOS_TMP_FOLDER/ios_cert_distribution.p12 -k "$KEYCHAIN_FULLNAME" -P "$IOS_DIST_CERT_P12_PASSWORD" -T "/usr/bin/codesign"
  security import $IOS_TMP_FOLDER/ios_cert_development.p12 -k "$KEYCHAIN_FULLNAME" -P "$IOS_DEV_CERT_P12_PASSWORD" -T "/usr/bin/codesign"

  # Check certificate was imported
  security find-identity -v -p codesigning "$KEYCHAIN_FULLNAME"

  # Detect the iOS identity
  IOS_IDENTITY=$(security find-identity -v -p codesigning "$KEYCHAIN_FULLNAME" | head -1 | grep '"' | sed -e 's/[^"]*"//' -e 's/".*//')
  IOS_UUID=$(security find-identity -v -p codesigning "$KEYCHAIN_FULLNAME" | head -1 | grep '"' | awk '{print $2}')

  # New requirement for MacOS 10.12
  security set-key-partition-list -S apple-tool:,apple: -s -k $IOS_KEYCHAIN_PASSWORD $KEYCHAIN_FULLNAME

  # Show signing keys
  security find-identity -v -p codesigning

  echo "$IOS_IDENTITY  $IOS_UUID"

  # SIGN APP
  # codesign -v -s "Apple Distribution: Rocket Lab Pty Ltd (YKXG58E5J6)" ./build/ios/iphoneos/Runner.app
}

ios_key_remove() {
  KEYCHAIN_FULLNAME="${IOS_KEYCHAIN_NAME}-db"
  security delete-keychain "$KEYCHAIN_FULLNAME"
  security find-identity -v -p codesigning
}

ios_key_create() {
  rm .ios_secrets/.DS_Store
  tar -zcvf ios_secrets.tgz $IOS_TMP_FOLDER
  echo "$IOS_KEYCHAIN_PASSWORD" | gpg --batch --yes --passphrase-fd 0 -c ios_secrets.tgz
  rm ios_secrets.tgz
}

ios_upload_ipa() {
  xcrun altool --upload-app --type ios -f build/ios/ipa/$IOS_IPA_FILE -u $IOS_UPLOAD_USER -p $IOS_UPLOAD_PASSWORD
}

generate_app_icon() {
  SOURCE_ICON=./assets/icon.png
  RESIZE_COMMAND="java -cp _tools/ resize_image"
  # hdpi 72
  # mdpi 48
  # xhdpi 96
  # xxhdpi 144
  # xxxhdpi 192
  javac _tools/resize_image.java 
  $RESIZE_COMMAND $SOURCE_ICON android/app/src/main/res/mipmap-hdpi/ic_launcher.png 72
  $RESIZE_COMMAND $SOURCE_ICON android/app/src/main/res/mipmap-mdpi/ic_launcher.png 48 
  $RESIZE_COMMAND $SOURCE_ICON android/app/src/main/res/mipmap-xhdpi/ic_launcher.png 96
  $RESIZE_COMMAND $SOURCE_ICON android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png 144
  $RESIZE_COMMAND $SOURCE_ICON android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png 192
}


generate_svg_icons() {
  rm ./src/components/icons/*.ts? ./src/components/svgimages/*.ts?
  ./node_modules/.bin/svgr --native --typescript --out-dir ./src/components/icons ./src/assets/icons/
  ./node_modules/.bin/svgr --native --typescript --out-dir ./src/components/svgimages ./src/assets/svg/
}


app_test() {
  SOURCE_ICON=./assets/icon.png
  # hdpi 72
  # mdpi 48
  # xhdpi 96
  # xxhdpi 144
  # xxxhdpi 192
  javac _tools/resize_image.java 
  java _tools/resize_image $SOURCE_ICON android/app/src/main/res/mipmap-hdpi/ic_launcher.png 72
  java _tools/resize_image $SOURCE_ICON android/app/src/main/res/mipmap-mdpi/ic_launcher.png 48 
  java _tools/resize_image $SOURCE_ICON android/app/src/main/res/mipmap-xhdpi/ic_launcher.png 96
  java _tools/resize_image $SOURCE_ICON android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png 144
  java _tools/resize_image $SOURCE_ICON android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png 192
}

# read environment from a file
if [ -f ./env.settings ]; then . ./env.settings; fi
if [ -f ./.env ]; then . ./.env; fi

# IOS management scripts
if [ "$1" = "ios-build" ]; then ios_build_ipa; exit; fi
if [ "$1" = "ios-key-add" ]; then ios_key_add; exit; fi
if [ "$1" = "ios-key-remove" ]; then ios_key_remove; exit; fi
if [ "$1" = "ios-key-check" ]; then codesign -dvvv $2; exit; fi
if [ "$1" = "ios-key-test" ]; then ios_get_secrets; exit; fi
if [ "$1" = "ios-key-create" ]; then ios_key_create; exit; fi
if [ "$1" = "ios-upload-ipa" ]; then ios_upload_ipa; exit; fi

# Android management scripts
if [ "$1" = "android-key-create" ]; then android_key_create; exit; fi
if [ "$1" = "android-key-test" ]; then android_key_test; exit; fi
if [ "$1" = "android-key-add" ]; then android_key_add; exit; fi
if [ "$1" = "android-key-remove" ]; then android_key_remove; exit; fi
if [ "$1" = "android-key-check" ]; then jarsigner -verify -verbose -certs $2; exit; fi

if [ "$1" = "patch" ]; then ios_patch_podfile; android_patch_app_build_gradle; exit; fi
if [ "$1" = "update-app-icon" ]; then generate_app_icon; exit; fi

if [ "$1" = "update-icons" ]; then generate_svg_icons; exit; fi

if [ "$1" = "test" ]; then app_test; exit; fi

echo "Command not found"
